language: python
python:
- '3.4'
- '3.5'
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: hxgFIsAtkMop3duuAN+MTlqxEmFVcFbb7b8ZAlOe0D5RcQmpIQquVnp3fMqfk1o57FiEF2DTAP69rCjJsaeiL2c725VAPqm3GXWbCbiOgyyDx/mhrxc9l2A8mEbntFmoceyyTAwVM7LrvzK83JPbuXhSHQWCFV9nKKC2qs1tfuDQEmEXEEG1KkEi6uOeNBREKrOfeOzc3ilE18eRhdIOVVRs7NQNy+qfLzEPNza2xOvp110GSbsoTUFHZSgZ5sinn+dU3oXdcquG0plzA6jF/4gbiLrbAOpihxF9VhZSnvwg0ZFIkDE9I+P8ZAoY7FrivLGNlUhTnKlP9Eeeg0LWkjrjxWlEeeaSuNZlJDxIvhM3OIMnkHtqPVviZ6PLf+/cxkEIm0aCHLi8u9fovMn+YqTFl0jpviPbAZI2sS8THCGH+bVcEDxGswXymkZpPOSmrpxahHeh7LS8qTNep/7u/EYPJW2nJyO/AT6CH/x1kjPFURNp6QdbbaEfYP2Gbbvj9uBxToAxWdJCtMgjY5GhjW4xyn6LQWIl4JosXTVv4SwQ91CO9yma/nrjKMw81aXzlVvOWOJfh3Hv6XOPH6tGXRGVckAMJA9Gc8aQENZRfHkSKxCpDq28z+8FP7DSc+qVZDzQNOzgPgdhaItnDYzxepNGGUiCgPg8B7ifKZC1Xrw=
  - secure: coDxReBaTwaVif5sANGMWAsAj5qul0miZtJxY1aihw+bgvqQVIM4Hlxs8EOhIwlARWxEq0CugZir/B2kWvMemZqd/1Ffn8gIveXVDel/BUcOOw4/uPCZTdo0EuOCUO7KqCgJ7w5m/rYM2wjMsthpMADVWuHGT5ajR6+vm5IxxxazQog0d/oShLjHQQubd8CBxmYWm8PrIIC2Liz2XXY+27CBMrWD4R6KTP2bIRqUbNXs9sXA3LOaGGRrocD64EjRaO41CApO8V76M3SqKHTUe4W0EIx+cMKi5ZOyixRb+jO2CExaiYy2wfnSPMN8RFkudQRQWB/otgKU6uO7Y+5K/V5XfvbT4BphW9hHrRUEexRa+KjoG8U8F4UYuqoNUTQn0IVq6cU7MU2sUqnM72WNAUAIzD+TFmU77bCl+T9TOT2esW6UG/DSjhCXEShAa3UfO9/XlEwjS1LaiXdGl7dxPoO7GEbsqGQS8XQtXGU7tXbZGDSkA/j28e0OGwcZXVQrZ1e5lbPMUWNZEgf4/8GsZ2z7BlDaSigSHFtmOLHarNxWiiyRF/5bkrTXqIkdQrdGw7s7gtuJUikoTHvi1CBAJAPggB1pGgw49gzQNKFolFqy/8riDMm1za/dGuscmJ6nwJCsB9NhmqCmNPbuXOBW0XceWzE4RHbX0+0jyu2AJtE=
  - LPW_RABBIT_HOST: localhost
  - LPW_RABBIT_EXCHANGE: travis.lcmap.changes.worker
  - LPW_RABBIT_QUEUE: travis.lcmap.changes.worker
before_install:
- make docker-deps-up
script: pytest
install:
- pip install --upgrade pip setuptools wheel
- pip install -e .
after_success:
- "/bin/bash deploy"
- make docker-deps-down
script: pytest
notifications:
  slack:
    rooms:
    - lcmap:UTqlh9PfPVomfpli10WKyZoh#cicd
